### ISSUE TITLE
SPI output stops after first packet on BeagleBone Black

### ISSUE THREAD

**Issue by adammhaile** [doceme/py-spidev#11]
I'm trying to communicate with an LPD8806 strip on my BBB using python and installed py-spidev (which is what I already use for the same code on a Raspberry Pi). I enabled SPI0 and have devices spidev1.0 and spidev1.1 (for whatever reason, on the latest debian, SPI0 is spidev1.* instead of spidev0.*).
When I send data to the SPI device with normal file access mode - open("/dev/spidev1.0", "wb") - it works fine. But when I use py-spidev like this:

```python
spi = spidev.SpiDev()
spi.open(1,0)
spi.xfer2(buffer)
```

It sends the first data packet and then never another one. It's not hanging or anything as xfer2 is returning just fine. But the later data never makes it to the strip.

Any ideas?

**Comment by Gadgetoid** [comment]
Did you ever find why this was the case? I understand that there's *supposed* to be a difference between xfer and xfer2 involving the chip-select line ( I don't think this is used in an LPD8806 strip? ), but that this difference doesn't occur on the Raspberry Pi.

**Comment by adammhaile** [comment]
Sadly, no... still doesn't work. Have to use file-mode SPI on BBB.

**Comment by sumikchakka** [comment]
can u share me the spi  device tree file adammhaile
