### ISSUE TITLE
AT91SAM9260 SPI Protocol Error during SPI transfer

### ISSUE THREAD

**Issue by raashidmuhammed** [doceme/py-spidev#13]
I used the py-spidev library in AT91SAM9260 board. I got the error **IOError: [Error 92]: Protocol not available** during SPI transfer. The problem was actually caused due to the Atmel SPI driver not supporting per transfer setting of *speed* and *bits_per_word*. So this quick fix in *spidev_module.c* solved the problem for me. I set the following variables in the *xfer* function to zero.
<pre><code>
+	xfer.speed_hz = 0;
+	xfer.bits_per_word = 0; 
</code></pre>
Is there a better fix for this problem? I would like to contribute a proper patch for this issue. Thank you.

**Comment by Gadgetoid** [comment]
If you set these values on spi before running a transfer, does it work? IE:

```
spi.max_speed_hz = 0
spi.bits_per_word = 0
spi.xfer([values])
```
