### ISSUE TITLE
What is the latest stable version of spi-dev and who is the master

### ISSUE THREAD

**Issue by framboosejh** [doceme/py-spidev#21]
I am searching for spi-dev for the raspberry 2 with kernel 3.18. And i see that there are two maintainers on  github, Gadgetoid and doceme. Which version is stable now and who is the master of spi-dev on github?

With regards,
Evert Jan Henken

**Comment by doceme** [comment]
I'm not sure where we left it, but Gadgetoid made a 3.0 release to PyPi here: https://pypi.python.org/pypi/spidev

I have only been testing with a Beaglebone Black and don't have a Raspberry Pi (1 or 2), so I am currently unable to test with those.  I don't have a lot of free time at the moment to dedicate to this project, so responses to issues will be slow.  I am happy to accept help from others that want to test on Raspberry Pi and also contribute patches.  If Gadgetoid is able to pick up the project and maintain it, I am happy to hand the reins to him.  If he isn't ready to take over, I will consider purchasing a Raspberry Pi 2 and try testing with it, but no promises on when that will be.
