### ISSUE TITLE
python interpreter memory leak using readbytes : i use xfer instead

### ISSUE THREAD

**Issue by albanmeffre** [doceme/py-spidev#24]
hello
i used readbytes in a while loop for polling spi. 
while True:
   r = spi.readbytes(Nbytes)    --> memory leak
   time.sleep(0.01)

while True:
   r = spi.xfer(Nbytes * [dummy byte])    --> no memory leak
   time.sleep(0.01)

thanks for supporting spidev.
AM

**Comment by doceme** [comment]
Okay, thanks for reporting this.  I'll look into it as soon as I can.

**Comment by doceme** [comment]
The memory leak should be fixed now. Can you test again with the latest commit?
