### ISSUE TITLE
All xfer2()s on MCP3008 return "TypeError: Argument must be a list of at least one, but not more than 4096 integers"

### ISSUE THREAD

**Issue by timwood0** [doceme/py-spidev#28]
I have followed numerous guides (that all agree) to wire up the MCP3008.  I breadboarded a simple pot sensing circuit.  The spidev/spi_bcm{2708,2835} drivers are installed and I tested MISO/MOSI with a direct test.  But I always get this message.  
Traceback (most recent call last):
  File "adafruit_mcp3008-spi.py", line 56, in <module>
    trim_pot = readadc(potentiometer_adc)
  File "adafruit_mcp3008-spi.py", line 36, in readadc
    r = spi.xfer2(commandout)
TypeError: Argument must ...

My test code: https://gist.github.com/timwood0/5e13fac6db4493cf4c85

BTW spidev_module.c confusingly uses the same error message for several different error cases!

Anyone see anything obviously wrong?  I tried running with tomstokes/python-spi library; the test reports bursts of noise values on the A/D output using that stack.

**Comment by timwood0** [comment]
PS As tdicola reports, development of py-spidev is supposed to have moved to Gadgetoid/py-spidev, but that repo does not allow issue reports and all changes since have happened here.

**Comment by timwood0** [comment]
PPS The bitbang code from Adafruit works as directed on my RPi+breadboard.

**Comment by doceme** [comment]
I'm not the best and noticing the nuances between Python 2 and Python 3. I added a proper fix to support int vs. long type checking.  Can you test with the latest commit on the master branch?

**Comment by doceme** [comment]
BTW, I haven't received a firm commitment from Gadgetoid about taking this thing over, so I'm still supporting it as I have time.

**Comment by timwood0** [comment]
Now that's service! :)

Your patch for the Int/Long check diffs between Python 2 & 3 seems to have fixed it.

I'll chip in the change to make the error messages more specific, and send a pull req., if you'd like.

Thank you, Doceme!

**Comment by doceme** [comment]
Great! Glad to hear it. I always appreciate pull requests.
