### ISSUE TITLE
"with" statement support

### ISSUE THREAD

**Issue by ArmlessJohn404** [doceme/py-spidev#32]
I've been searching for some documentation to implement `with` statement support for `SpiDev` and couldn't find much. 
Is there interest in adding this feature?  If you point me some directions I can create a PR for that.

**Comment by doceme** [comment]
I think that's a good idea, but not something I'm planning to work on anytime soon.  Feel free to create a PR for it if you get it working.

**Comment by ArmlessJohn404** [comment]
I'm not quite comfortable writing `python` extensions in `C`, I'll take another look. Do you know any resources I can read about the `with` statement?

**Comment by doceme** [comment]
I don't expect you to implement it, but just wanted to warn you that I probably won't have time to add support for this soon.  It looks like two new functions would need to be defined called "__enter__" and "__exit__".  Have a look at this discussion: http://www.gossamer-threads.com/lists/python/python/949495 and this code as an example: https://github.com/jolicloud/python-apt/blob/master/python/lock.cc

Something similar would need to be added.

**Comment by doceme** [comment]
Looks like github strips out the underscores.  There are supposed to be two underscore characters before and after the __enter__ and __exit__ above.

**Comment by ArmlessJohn404** [comment]
ok! thanks!
