### ISSUE TITLE
package extension

### ISSUE THREAD

**Issue by ArmlessJohn404** [doceme/py-spidev#33]
I'm implementing a [library](https://github.com/ArmlessJohn404/RPi_mcp3008) for the MCP3008 A/D converter chip. 
It just implements the example communication protocol in the [datasheet](https://www.adafruit.com/datasheets/MCP3008.pdf) inheriting `SpiDev`.
Is there interest in creating an `extension` folder for the package to add support for devices like these?

**Comment by doceme** [comment]
There are an endless number of chips that this library could potentially communicate with.  I think that code would be best served in another repository.  Feel free to create one and reference this one, or fork this one if you don't agree.

**Comment by ArmlessJohn404** [comment]
Allright! thanks
