### ISSUE TITLE
Device filename is different in code, comment and documentation.

### ISSUE THREAD

**Issue by ponty** [doceme/py-spidev#37]
README.md 
".. opening /dev/spidev-bus.device .."

spidev_module.c
".. file descriptor: /dev/spi-X.Y .."

".. will open /dev/spidev-X.Y .."

"/dev/spidev%d.%d"

**Comment by Gadgetoid** [comment]
The correct format is `/dev/spidev<bus>.<device>`, will get this tidied up and submit a PR!

**Comment by ponty** [comment]
Fixed in 11adf8c976c58ad15e002bfa57ed7f7950a89435
