### ISSUE TITLE
How to add delay between tranfer

### ISSUE THREAD

**Issue by droorzn** [doceme/py-spidev#4]
i use your project to make a communication between Raspberry Pi (MASTER) and AVR (SLAVE). I noticed the data from raspberry is sucessfully sent but the data from AVR only the first communication success. Rest of the byte is read as what i send, i think AVR  don't have enough time to  to change SPI Data Register or SPDR before being read by the Raspberry.
so i want to add a delay, i found the delay_usec in the spi.xfer but how i change it. thanks

**Comment by dany0792** [comment]
Hi, 
I use your project(spidev 3.4) to make a communication between (personal development board) and (ASUS Tinker Board S). I use xfer2 function to read spi data on ASUS Board from my board. So i want to add a delay_usec, i found the delay_usec in the spi.xfer2 but it is not working for me. I have tried several ways to add this delay, but I didn't succeed. 
One of my attempts I used is:

spi = spidev.SpiDev()
spi.open(2,0) 
spi.mode = 1
#spi.max_speed_hz = 250000
spiResp = spi.xfer2(spiData, 250000, 1000, 8)

or:
#spiResp = spi.xfer2([1])
#spiData = range(spiResp[0])
#spiResp = spi.xfer2(spiData, 250000, 1000)

Please, help me with that ...
Thank you!
