### ISSUE TITLE
SpiDev_open cannot handle keyword argument ‘device’ correctly

### ISSUE THREAD

**Issue by XIVN1987** [doceme/py-spidev#52]
`spi = spidev.SpiDev(bus=0, device=0)`

TypeError: 'device' is an invalid keyword argument for this function

**Comment by alexpeits** [comment]
By looking at [`__init__`](https://github.com/doceme/py-spidev/blob/master/spidev_module.c#L938), I think it only accepts `bus` and `client` as arguments. `device` is an argument for the [`open`](https://github.com/doceme/py-spidev/blob/master/spidev_module.c#L901) method.
