### ISSUE TITLE
increase SPI clock speed

### ISSUE THREAD

**Issue by Ogg3l** [doceme/py-spidev#69]
Hello everybody,

how can i increase the clock speed or the CDIV (Clock Divider) see: https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md? 

is there an option? 

Thanks :)

**Comment by semininja** [comment]
If you take a look at the README for py-spidev, you'll see the ’max-speed-hz’ option, which can be used to set the clock speed for SPI transactions.

**Comment by semininja** [comment]
To put it more bluntly, RTFM :)

**Comment by Ogg3l** [comment]
Thanks :)
