### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by jacmet** [doceme/py-spidev#89]
The license was changed in https://github.com/doceme/py-spidev/commit/611b74341f44d444670fd373b1fb755ea2589718 but setup.py still states GPLv2 and the LICENSE file is not included in the tarball.

It would be great to have MIT everywhere and include the license file in the tarball, thanks

**Comment by ledmonster** [comment]
Also, I would appreciate if you would release a new version (v3.4 or v3.3.1) with new license, thank you.
